"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from django.urls import reverse_lazy
from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from celery.schedules import crontab
from firebase_admin import initialize_app
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file, or switch to system
try:
    dotenv_path = os.path.join(BASE_DIR, '.env')
    load_dotenv(dotenv_path)
except Exception as e:
    print(f"Unable to load file: {dotenv_path}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Discord
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
DISCORD_CHANNEL_ID = int(os.getenv("DISCORD_CHANNEL_ID")) if os.getenv("DISCORD_CHANNEL_ID") else None

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGOSECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv('DEBUG') == 'True' else False

ALLOWED_HOSTS = [os.getenv('ALLOWED_HOST')]

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT', 25)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

ACCOUNT_MAX_EMAIL_ADDRESSES = 1

# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',
    'modeltranslation',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    'unfold.contrib.location_field',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'django_celery_beat',
    'corsheaders',
    'mfa',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'django_filters',
    'dj_rest_auth.registration',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    # 'dj_rest_auth_mfa',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_celery_results',
    'fcm_django',
    'location_field',
    'consultations',
    'users',
    'messaging',
    'mediaserver',
    'api',
]

NOTIFICATION_MESSAGES = [
    ('you_have_been_assigned_to_consultation', _(
        'Message sent to user when assigned to a consultation')),
    ('an_unprocessed_request_has_been_received', _(
        'Message sent to user when a consultation request requires manual processing')),
    ('a_message_has_been_sent_by_beneficiary', _(
        'Message sent to user when a beneficiary sends a message')),
    ('invitation_to_join_consultation_now', _(
        'Message sent to user with invitation to join a consultation immediately')),
    ('invitation_to_join_consultation_later', _(
        'Message sent to user with invitation to join a consultation at a later time')),
    ('your_appointment_is_in_24h', _(
        'Message sent to user 24 hours before scheduled appointment')),
    ('your_authentication_code_is_participant', _(
        'Message sent to participant containing their authentication code')),
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TimezoneMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ASGI_APPLICATION = "core.asgi.application"

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "core/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', 'upload')
MEDIA_URL = '/upload/'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

gettext = lambda s: s
LANGUAGES = (
    ('en', gettext('English')),
    ('de', gettext('German')),
    ('fr', gettext('French')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

SITE_ID = 1
ACCOUNT_EMAIL_VERIFICATION = "optional"
AUTH_USER_MODEL = 'users.User'

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': '_auth',
    'JWT_AUTH_REFRESH_COOKIE': '_refresh',
    'JWT_AUTH_HTTPONLY': False,
    'USER_DETAILS_SERIALIZER': 'users.serializers.UserDetailsSerializer',
    'REGISTER_SERIALIZER': 'users.serializers.RegisterSerializer',
    'LOGIN_SERIALIZER': 'users.serializers.LoginSerializer',
}

LOGIN_REDIRECT_URL = '/home/'

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'basic': {
            'type': 'oauth2'
        }
    },
    'USE_SESSION_AUTH': False

}

SPECTACULAR_SETTINGS = {
    'TITLE': 'HCW@Home API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {  # OpenAPI 3
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "SECURITY": [{"bearerAuth": []}],  # apply globally
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,  # <-- keep JWT after refresh
        # "tryItOutEnabled": True,     # optional
    },
}

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": 'openid',
                "name": os.getenv('OPENID_NAME'),
                "client_id": os.getenv('OPENID_CLIENT_ID'),
                "secret": os.getenv('OPENID_SECRET'),
                "settings": {
                    "server_url": os.getenv('OPENID_CONFIGURATION_URL'),
                },
            }
        ]
    }
}

SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

REDIS_HOST = os.getenv('REDIS_HOST') or '127.0.0.1'
REDIS_PORT = os.getenv('REDIS_PORT') or '6379'

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache" if not DEBUG else 'django.core.cache.backends.locmem.LocMemCache',
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}",
    }
}
STATIC_ROOT = os.getenv('STATIC_ROOT', 'statics')

CELERY_BEAT_SCHEDULE = {
    # 'run_all': {
    #     'task': 'module.tasks.run_all',
    #     'schedule': crontab(minute=0, hour='*'),
    # },
}

FIREBASE_APP = initialize_app()

FCM_DJANGO_SETTINGS = {
    "ONE_DEVICE_PER_USER": False,
    "DELETE_INACTIVE_DEVICES": True,
    "FCM_DEVICE_MODEL": "users.FCMDeviceOverride",
}

ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')

# Janus Media Server Configuration
JANUS_TURN_SERVER = os.getenv('JANUS_TURN_SERVER', 'turn:demo.hcw-at-home.com')
JANUS_TURN_USERNAME = os.getenv('JANUS_TURN_USERNAME', 'iabsis')
JANUS_TURN_PASSWORD = os.getenv('JANUS_TURN_PASSWORD', 'pfcqopfs')

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, 6379)],
        },
    },
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Unfold Admin Configuration
UNFOLD = {
    "SHOW_LANGUAGES": True,
    "SITE_TITLE": _("HCW@Home Admin"),
    "SITE_HEADER": _("HCW@Home Administration"),
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "core.views.dashboard_callback",
    "SITE_ICON": {
        "light": lambda request: "/static/users/img/logo-full.svg",
        "dark": lambda request: "/static/users/img/logo-full.svg",
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": _("Users & Authentication"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": "/admin/users/user/",
                        "permission": lambda request: request.user.has_perm("users.view_user"),
                    },
                    {
                        "title": _("Health Metric"),
                        "icon": "people",
                        "link": "/admin/users/healthmetric/",
                        "permission": lambda request: request.user.has_perm("users.view_healthmetric"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": "/admin/auth/group/",
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                    {
                        "title": _("Organizations"),
                        "icon": "business",
                        "link": "/admin/users/organisation/",
                        "permission": lambda request: request.user.has_perm("users.view_organisation"),
                    },
                    {
                        "title": _("Terms"),
                        "icon": "contract",
                        "link": "/admin/users/term/",
                        "permission": lambda request: request.user.has_perm("users.view_term"),
                    },
                    {
                        "title": _("Languages"),
                        "icon": "language",
                        "link": "/admin/users/language/",
                        "permission": lambda request: request.user.has_perm("users.view_language"),
                    },
                    {
                        "title": _("Specialities"),
                        "icon": "medical_services",
                        "link": "/admin/users/speciality/",
                        "permission": lambda request: request.user.has_perm("users.view_speciality"),
                    },
                    {
                        "title": _("Notifications"),
                        "icon": "notifications",
                        "link": "/admin/users/notification/",
                        "permission": lambda request: request.user.has_perm("users.view_notification"),
                    },
                    {
                        "title": _("FCM Devices"),
                        "icon": "phone_android",
                        "link": "/admin/users/fcmdeviceoverride/",
                        "permission": lambda request: request.user.has_perm("users.view_fcmdeviceoverride"),
                    },
                ],
            },
            {
                "title": _("Consultations"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Consultations"),
                        "icon": "medical_services",
                        "link": "/admin/consultations/consultation/",
                        "permission": lambda request: request.user.has_perm("consultations.view_consultation"),
                    },
                    {
                        "title": _("Queues"),
                        "icon": "group_work",
                        "link": "/admin/consultations/queue/",
                        "permission": lambda request: request.user.has_perm("consultations.view_queue"),
                    },
                    {
                        "title": _("Appointments"),
                        "icon": "schedule",
                        "link": "/admin/consultations/appointment/",
                        "permission": lambda request: request.user.has_perm("consultations.view_appointment"),
                    },
                    {
                        "title": _("Messages"),
                        "icon": "message",
                        "link": "/admin/consultations/message/",
                        "permission": lambda request: request.user.has_perm("consultations.view_message"),
                    },
                    {
                        "title": _("Reasons"),
                        "icon": "list",
                        "link": "/admin/consultations/reason/",
                        "permission": lambda request: request.user.has_perm("consultations.view_reason"),
                    },
                    {
                        "title": _("Requests"),
                        "icon": "inbox",
                        "link": "/admin/consultations/request/",
                        "permission": lambda request: request.user.has_perm("consultations.view_request"),
                    },
                    {
                        "title": _("Booking slots"),
                        "icon": "event",
                        "link": "/admin/consultations/bookingslot/",
                        "permission": lambda request: request.user.has_perm("consultations.view_bookingslot"),
                    },
                ],
            },
            {
                "title": _("Messaging"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Messaging providers"),
                        "icon": "settings_applications",
                        "link": "/admin/messaging/messagingprovider/",
                        "permission": lambda request: request.user.has_perm("messaging.view_messagingprovider"),
                    },
                    {
                        "title": _("Messages"),
                        "icon": "message",
                        "link": "/admin/messaging/message/",
                        "permission": lambda request: request.user.has_perm("messaging.view_messagingprovider"),
                    },
                    {
                        "title": _("Templates"),
                        "icon": "description",
                        "link": "/admin/messaging/template/",
                        "permission": lambda request: request.user.has_perm("messaging.view_template"),
                    },
                    {
                        "title": _("Template Validations"),
                        "icon": "verified",
                        "link": "/admin/messaging/templatevalidation/",
                        "permission": lambda request: request.user.has_perm("messaging.view_templatevalidation"),
                    },
                ],
            },
            {
                "title": _("Media & API"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Media Server"),
                        "icon": "videocam",
                        "link": "/admin/mediaserver/server/",
                        "permission": lambda request: request.user.has_perm("mediaserver.view_server"),
                    },
                    {
                        "title": _("TURN Server"),
                        "icon": "router",
                        "link": "/admin/mediaserver/turn/",
                        "permission": lambda request: request.user.has_perm("mediaserver.view_turn"),
                    },
                ],
            },
            {
                "title": _("Celery Tasks"),
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": _("Clocked"),
                        "icon": "hourglass_bottom",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_clockedschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Crontabs"),
                        "icon": "update",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_crontabschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Intervals"),
                        "icon": "timer",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_intervalschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Periodic tasks"),
                        "icon": "task",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_periodictask_changelist"
                        ),
                    },
                    {
                        "title": _("Solar events"),
                        "icon": "event",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_solarschedule_changelist"
                        ),
                    },
                ],
            },
            # {
            #     "title": _("Settings"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Configuration"),
            #             "icon": "settings",
            #             "link": "/admin/configuration/configuration/",
            #             "permission": lambda request: request.user.has_perm("configuration.view_configuration"),
            #         },
            #     ],
            # },
        ],
    },
}

# Default Configuration Values
DEFAULT_CONFIGURATIONS = {
    'site_name': {
        'value': 'HCW@Home',
        'description': 'The name of the application displayed to users',
    },
    'site_url': {
        'value': 'https://localhost:8000',
        'description': 'Base URL of the application',
    },
    'max_upload_size': {
        'value': '10485760',  # 10MB in bytes
        'description': 'Maximum file upload size in bytes',
    },
    'maintenance_mode': {
        'value': 'false',
        'description': 'Enable/disable maintenance mode (true/false)',
    },
    'contact_email': {
        'value': 'admin@example.com',
        'description': 'Contact email for support inquiries',
    },
    'session_timeout': {
        'value': '3600',  # 1 hour in seconds
        'description': 'Session timeout in seconds',
    },
    'enable_notifications': {
        'value': 'true',
        'description': 'Enable/disable push notifications (true/false)',
    },
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in DEBUG mode
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = []
# Add specific origins here for production when DEBUG=False
# Example: 'https://yourdomain.com', 'https://www.yourdomain.com'
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

PRACTITIONER_URL = os.getenv('PRACTITIONER_URL', 'http://localhost:4200')
PATIENT_URL = os.getenv('PATIENT_URL', 'http://localhost:4201')


# RECOVERY_ITERATION = 720000 
# MFA_MANDATORY = False
# MFA_ADAPTER_CLASS = "dj_rest_auth_mfa.adapters.DjangoMFA2Adapter"
# MFA_GRACE_WINDOW_DAYS = 7

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
