"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
from firebase_admin import initialize_app

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file, or switch to system
try:
    dotenv_path = os.path.join(BASE_DIR, ".env")
    load_dotenv(dotenv_path)
except Exception as e:
    print(f"Unable to load file: {dotenv_path}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Discord
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
DISCORD_CHANNEL_ID = (
    int(os.getenv("DISCORD_CHANNEL_ID")) if os.getenv("DISCORD_CHANNEL_ID") else None
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGOSECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("DEBUG") == "True" else False

ALLOWED_HOSTS = [os.getenv("ALLOWED_HOST")]

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT", 25)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", False)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# Clamav Antivirus
if os.getenv("CLAMD_SOCKET"):
    CLAMD_USE_TCP = False
    CLAMD_SOCKET = os.getenv("CLAMD_SOCKET", "/var/run/clamav/clamd.ctl")

elif os.getenv("CLAMD_TCP_ADDR"):
    CLAMD_USE_TCP = True
    CLAMD_TCP_SOCKET = int(os.getenv("CLAMD_TCP_SOCKET", 3310))
    CLAMD_TCP_ADDR = os.getenv("CLAMD_TCP_ADDR", "127.0.0.1")
else:
    CLAMD_ENABLED = False

ACCOUNT_MAX_EMAIL_ADDRESSES = 1

# Application definition

INSTALLED_APPS = [
    "daphne",
    "unfold",
    "modeltranslation",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.location_field",
    "unfold.contrib.constance",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    "django_celery_beat",
    "corsheaders",
    "mfa",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
    "django_filters",
    "dj_rest_auth.registration",
    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    # 'dj_rest_auth_mfa',
    "rest_framework_simplejwt",
    "drf_spectacular",
    "django_celery_results",
    "fcm_django",
    "location_field",
    "consultations",
    "users",
    "messaging",
    "mediaserver",
    "api",
    "constance",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.TimezoneMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ASGI_APPLICATION = "core.asgi.application"

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", "upload")
MEDIA_URL = "/upload/"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DATABASE_NAME"),
        "USER": os.getenv("DATABASE_USER"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),
        "HOST": os.getenv("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT"),
    }
}

SIMPLE_JWT = {"ACCESS_TOKEN_LIFETIME": timedelta(days=1), "ROTATE_REFRESH_TOKENS": True}

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

gettext = lambda s: s
LANGUAGES = (
    ("en", gettext("English")),
    ("de", gettext("German")),
    ("fr", gettext("French")),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

SITE_ID = 1
ACCOUNT_EMAIL_VERIFICATION = "optional"
AUTH_USER_MODEL = "users.User"

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "_auth",
    "JWT_AUTH_REFRESH_COOKIE": "_refresh",
    "JWT_AUTH_HTTPONLY": False,
    "USER_DETAILS_SERIALIZER": "users.serializers.UserDetailsSerializer",
    "REGISTER_SERIALIZER": "users.serializers.RegisterSerializer",
    "LOGIN_SERIALIZER": "users.serializers.LoginSerializer",
}

LOGIN_REDIRECT_URL = "/home/"

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {"basic": {"type": "oauth2"}},
    "USE_SESSION_AUTH": False,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "HCW@Home API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {  # OpenAPI 3
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "SECURITY": [{"bearerAuth": []}],  # apply globally
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,  # <-- keep JWT after refresh
        # "tryItOutEnabled": True,     # optional
    },
}

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "openid",
                "name": os.getenv("OPENID_NAME"),
                "client_id": os.getenv("OPENID_CLIENT_ID"),
                "secret": os.getenv("OPENID_SECRET"),
                "settings": {
                    "server_url": os.getenv("OPENID_CONFIGURATION_URL"),
                },
            }
        ]
    }
}

SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

REDIS_HOST = os.getenv("REDIS_HOST") or "127.0.0.1"
REDIS_PORT = os.getenv("REDIS_PORT") or "6379"

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache"
        if not DEBUG
        else "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}",
    }
}
STATIC_ROOT = os.getenv("STATIC_ROOT", "statics")

CELERY_BEAT_SCHEDULE = {
    # 'run_all': {
    #     'task': 'module.tasks.run_all',
    #     'schedule': crontab(minute=0, hour='*'),
    # },
}

FIREBASE_APP = initialize_app()

FCM_DJANGO_SETTINGS = {
    "ONE_DEVICE_PER_USER": False,
    "DELETE_INACTIVE_DEVICES": True,
    "FCM_DEVICE_MODEL": "users.FCMDeviceOverride",
}

ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY")

# Janus Media Server Configuration
JANUS_TURN_SERVER = os.getenv("JANUS_TURN_SERVER", "turn:demo.hcw-at-home.com")
JANUS_TURN_USERNAME = os.getenv("JANUS_TURN_USERNAME", "iabsis")
JANUS_TURN_PASSWORD = os.getenv("JANUS_TURN_PASSWORD", "pfcqopfs")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, 6379)],
        },
    },
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Unfold Admin Configuration
UNFOLD = {
    "SHOW_LANGUAGES": True,
    "SITE_TITLE": _("HCW@Home Admin"),
    "SITE_HEADER": _("HCW@Home Administration"),
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "core.views.dashboard_callback",
    "SITE_ICON": {
        "light": lambda request: "/static/users/img/logo-full.svg",
        "dark": lambda request: "/static/users/img/logo-full.svg",
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Users & Authentication"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:users_user_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "users.view_user"
                        ),
                    },
                    {
                        "title": _("Health Metric"),
                        "icon": "people",
                        "link": reverse_lazy("admin:users_healthmetric_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "users.view_healthmetric"
                        ),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "auth.view_group"
                        ),
                    },
                    {
                        "title": _("Organizations"),
                        "icon": "business",
                        "link": reverse_lazy("admin:users_organisation_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "users.view_organisation"
                        ),
                    },
                    {
                        "title": _("Terms"),
                        "icon": "contract",
                        "link": reverse_lazy("admin:users_term_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "users.view_term"
                        ),
                    },
                    {
                        "title": _("Languages"),
                        "icon": "language",
                        "link": reverse_lazy("admin:users_language_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "users.view_language"
                        ),
                    },
                    {
                        "title": _("Specialities"),
                        "icon": "medical_services",
                        "link": reverse_lazy("admin:users_speciality_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "users.view_speciality"
                        ),
                    },
                    {
                        "title": _("Notifications"),
                        "icon": "notifications",
                        "link": reverse_lazy("admin:users_notification_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "users.view_notification"
                        ),
                    },
                    {
                        "title": _("FCM Devices"),
                        "icon": "phone_android",
                        "link": reverse_lazy(
                            "admin:users_fcmdeviceoverride_changelist"
                        ),
                        "permission": lambda request: request.user.has_perm(
                            "users.view_fcmdeviceoverride"
                        ),
                    },
                ],
            },
            {
                "title": _("Consultations"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Consultations"),
                        "icon": "medical_services",
                        "link": reverse_lazy(
                            "admin:consultations_consultation_changelist"
                        ),
                        "permission": lambda request: request.user.has_perm(
                            "consultations.view_consultation"
                        ),
                    },
                    {
                        "title": _("Queues"),
                        "icon": "group_work",
                        "link": reverse_lazy("admin:consultations_queue_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "consultations.view_queue"
                        ),
                    },
                    {
                        "title": _("Appointments"),
                        "icon": "schedule",
                        "link": reverse_lazy(
                            "admin:consultations_appointment_changelist"
                        ),
                        "permission": lambda request: request.user.has_perm(
                            "consultations.view_appointment"
                        ),
                    },
                    {
                        "title": _("Messages"),
                        "icon": "message",
                        "link": reverse_lazy("admin:consultations_message_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "consultations.view_message"
                        ),
                    },
                    {
                        "title": _("Reasons"),
                        "icon": "list",
                        "link": reverse_lazy("admin:consultations_reason_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "consultations.view_reason"
                        ),
                    },
                    {
                        "title": _("Requests"),
                        "icon": "inbox",
                        "link": reverse_lazy("admin:consultations_request_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "consultations.view_request"
                        ),
                    },
                    {
                        "title": _("Booking slots"),
                        "icon": "event",
                        "link": reverse_lazy(
                            "admin:consultations_bookingslot_changelist"
                        ),
                        "permission": lambda request: request.user.has_perm(
                            "consultations.view_bookingslot"
                        ),
                    },
                ],
            },
            {
                "title": _("Messaging"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Messaging providers"),
                        "icon": "settings_applications",
                        "link": reverse_lazy(
                            "admin:messaging_messagingprovider_changelist"
                        ),
                        "permission": lambda request: request.user.has_perm(
                            "messaging.view_messagingprovider"
                        ),
                    },
                    {
                        "title": _("Messages"),
                        "icon": "message",
                        "link": reverse_lazy("admin:messaging_message_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "messaging.view_messagingprovider"
                        ),
                    },
                    {
                        "title": _("Templates"),
                        "icon": "description",
                        "link": reverse_lazy("admin:messaging_template_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "messaging.view_template"
                        ),
                    },
                    {
                        "title": _("Template Validations"),
                        "icon": "verified",
                        "link": reverse_lazy(
                            "admin:messaging_templatevalidation_changelist"
                        ),
                        "permission": lambda request: request.user.has_perm(
                            "messaging.view_templatevalidation"
                        ),
                    },
                ],
            },
            {
                "title": _("Media & API"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Media Server"),
                        "icon": "videocam",
                        "link": reverse_lazy("admin:mediaserver_server_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "mediaserver.view_server"
                        ),
                    },
                    {
                        "title": _("TURN Server"),
                        "icon": "router",
                        "link": reverse_lazy("admin:mediaserver_turn_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "mediaserver.view_turn"
                        ),
                    },
                ],
            },
            {
                "title": _("Celery Tasks"),
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": _("Clocked"),
                        "icon": "hourglass_bottom",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_clockedschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Crontabs"),
                        "icon": "update",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_crontabschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Intervals"),
                        "icon": "timer",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_intervalschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Periodic tasks"),
                        "icon": "task",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_periodictask_changelist"
                        ),
                    },
                    {
                        "title": _("Solar events"),
                        "icon": "event",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_solarschedule_changelist"
                        ),
                    },
                ],
            },
            # {
            #     "title": _("Settings"),
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": _("Configuration"),
            #             "icon": "settings",
            #             "link": "/admin/configuration/configuration/",
            #             "permission": lambda request: request.user.has_perm("configuration.view_configuration"),
            #         },
            #     ],
            # },
        ],
    },
}

# Default Configuration Values
CONSTANCE_CONFIG = {
    "site_name": ("HCW@Home", "The name of the application displayed to users"),
    "patient_base_url": ("https://localhost:8000", "Base URL of patient frontend"),
    "practionner_base_url": (
        "https://localhost:8000",
        "Base URL of practionner frontend",
    ),
}


CONSTANCE_CONFIG_FIELDSETS = {
    "General Options": ("site_name",),
    "URLs": ("patient_base_url", "practionner_base_url"),
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in DEBUG mode
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = []
# Add specific origins here for production when DEBUG=False
# Example: 'https://yourdomain.com', 'https://www.yourdomain.com'
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

PRACTITIONER_URL = os.getenv("PRACTITIONER_URL", "http://localhost:4200")
PATIENT_URL = os.getenv("PATIENT_URL", "http://localhost:4201")


# RECOVERY_ITERATION = 720000
# MFA_MANDATORY = False
# MFA_ADAPTER_CLASS = "dj_rest_auth_mfa.adapters.DjangoMFA2Adapter"
# MFA_GRACE_WINDOW_DAYS = 7

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
