# Generated by Django 5.2.6 on 2025-09-10 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Online', 'Online'), ('InPerson', 'In person')], default='Online')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', verbose_name='status')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('end_expected_at', models.DateTimeField(blank=True, null=True, verbose_name='end expected at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('end_time', models.TimeField(default=datetime.time(18, 0))),
                ('start_break', models.TimeField(blank=True, default=datetime.time(12, 0), null=True)),
                ('end_break', models.TimeField(blank=True, default=datetime.time(14, 0), null=True)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('valid_until', models.DateField(blank=True, help_text='Slot valid until this date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('description', models.CharField(blank=True, null=True, verbose_name='description')),
                ('title', models.CharField(blank=True, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages_attachment', verbose_name='attachment')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=256)),
                ('is_invited', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], max_length=20)),
                ('feedback_rate', models.IntegerField(blank=True, null=True)),
                ('feedback_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_de', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'queue',
                'verbose_name_plural': 'queues',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='name')),
                ('name_en', models.CharField(null=True, verbose_name='name')),
                ('name_de', models.CharField(null=True, verbose_name='name')),
                ('name_fr', models.CharField(null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes', verbose_name='duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('assignment_method', models.CharField(choices=[('User', 'User'), ('Queue', 'Queue'), ('Appointment', 'Appointment')], default='Appointment')),
            ],
            options={
                'verbose_name': 'reason',
                'verbose_name_plural': 'reasons',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Online', 'Online'), ('InPerson', 'In person')], default='Online')),
                ('comment', models.TextField()),
                ('refused_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Refused', 'Refused')], default='Requested')),
            ],
        ),
    ]
