# Generated by Django 5.2.6 on 2025-09-10 10:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('consultations', '0001_initial'), ('consultations', '0002_rename_schedule_date_consultation_scheduled_date'), ('consultations', '0003_queuegroup'), ('consultations', '0004_rename_organisation_id_queuegroup_organisation'), ('consultations', '0005_remove_queuegroup_organisation_and_more'), ('consultations', '0006_remove_consultation_scheduled_date_and_more'), ('consultations', '0007_rename_queuegroup_group_consultation_group'), ('consultations', '0008_alter_message_options_remove_message_particiant_id_and_more'), ('consultations', '0009_message_celery_task_id_message_task_logs_and_more'), ('consultations', '0010_alter_consultation_beneficiary'), ('consultations', '0011_alter_message_options_remove_message_celery_task_id_and_more'), ('consultations', '0012_alter_message_sent_by'), ('consultations', '0013_alter_message_attachment_alter_message_content'), ('consultations', '0014_rename_sent_by_message_created_by'), ('consultations', '0015_alter_appointment_consultation'), ('consultations', '0016_appointment_created_at_appointment_created_by'), ('consultations', '0017_reason'), ('consultations', '0018_appointment_status'), ('consultations', '0019_alter_reason_speciality'), ('consultations', '0020_reason_is_active'), ('consultations', '0021_request_consultation_request'), ('consultations', '0022_rename_requested_by_request_created_by_and_more'), ('consultations', '0023_request_expected_with_alter_consultation_request_and_more'), ('consultations', '0024_remove_consultation_request_request_appointment_and_more'), ('consultations', '0025_slot_consultation_description_consultation_title_and_more'), ('consultations', '0026_rename_token_participant_auth_token_and_more'), ('consultations', '0027_request_type_alter_request_status'), ('consultations', '0028_slot_user'), ('consultations', '0029_bookingslot_delete_slot'), ('consultations', '0030_bookingslot_created_by_request_beneficiary'), ('consultations', '0031_alter_bookingslot_end_break_and_more'), ('consultations', '0032_alter_bookingslot_valid_until'), ('consultations', '0033_rename_thurday_bookingslot_thursday'), ('consultations', '0034_alter_appointment_consultation'), ('consultations', '0035_participant_is_confirmed'), ('consultations', '0036_rename_group_queue_and_more'), ('consultations', '0037_alter_queue_organisation'), ('consultations', '0038_alter_bookingslot_end_break_and_more'), ('consultations', '0039_alter_queue_organisation'), ('consultations', '0040_alter_appointment_options_alter_consultation_options_and_more'), ('consultations', '0041_consultation_type'), ('consultations', '0042_remove_consultation_type_appointment_type'), ('consultations', '0043_request_refused_reason_alter_request_status'), ('consultations', '0044_reason_assignment_method'), ('consultations', '0045_alter_request_consultation'), ('consultations', '0046_alter_reason_assignment_method'), ('consultations', '0047_alter_request_reason'), ('consultations', '0048_alter_request_expected_at'), ('consultations', '0049_alter_appointment_options_alter_consultation_options'), ('consultations', '0050_queue_name_af_queue_name_ar_queue_name_ar_dz_and_more'), ('consultations', '0051_remove_queue_name_af_remove_queue_name_ar_and_more'), ('consultations', '0052_alter_queue_users')]

    initial = True

    dependencies = [
        ('users', '0003_rename_specialites_user_specialities'),
        ('users', '0011_organisation_alter_user_main_organisation_and_more'),
        ('users', '0016_alter_speciality_options_alter_speciality_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='beneficiary')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.group')),
                ('description', models.CharField(blank=True, null=True, verbose_name='description')),
                ('title', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('end_expected_at', models.DateTimeField(blank=True, null=True, verbose_name='end expected at')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultations.consultation', verbose_name='consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', verbose_name='status')),
                ('type', models.CharField(choices=[('Online', 'Online'), ('InPerson', 'In person')], default='Online')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=256)),
                ('is_invited', models.BooleanField(default=True)),
                ('feedback_rate', models.IntegerField(blank=True, null=True)),
                ('feedback_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appointement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], default=None, max_length=20)),
                ('phone', models.CharField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='users')),
                ('organisation', models.ManyToManyField(blank=True, to='users.organisation', verbose_name='organisation')),
                ('name_de', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'queue',
                'verbose_name_plural': 'queues',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes', verbose_name='duration')),
                ('queue_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.queue', verbose_name='queue assignee')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='users.speciality', verbose_name='speciality')),
                ('user_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user assignee')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('assignment_method', models.CharField(choices=[('User', 'User'), ('Queue', 'Queue'), ('Appointment', 'Appointment')], default='Appointment')),
                ('name_de', models.CharField(null=True, verbose_name='name')),
                ('name_en', models.CharField(null=True, verbose_name='name')),
                ('name_fr', models.CharField(null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'reason',
                'verbose_name_plural': 'reasons',
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('end_time', models.TimeField(default=datetime.time(18, 0))),
                ('start_break', models.TimeField(blank=True, default=datetime.time(12, 0), null=True)),
                ('end_break', models.TimeField(blank=True, default=datetime.time(14, 0), null=True)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('valid_until', models.DateField(blank=True, help_text='Slot valid until this date', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.queue', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='owned by'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='title',
            field=models.CharField(blank=True, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultation', verbose_name='consultation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages_attachment', verbose_name='attachment')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasons', to='consultations.reason')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_asrequester', to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Refused', 'Refused')], default='Requested')),
                ('expected_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_asexpected', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.appointment')),
                ('consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='consultations.consultation')),
                ('type', models.CharField(choices=[('Online', 'Online'), ('InPerson', 'In person')], default='Online')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_asbeneficiary', to=settings.AUTH_USER_MODEL)),
                ('refused_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at'], 'verbose_name': 'consultation', 'verbose_name_plural': 'consultations'},
        ),
    ]
