# Generated by Django 5.1.4 on 2025-08-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='schedule_date',
            new_name='scheduled_date',
        ),
    ]
