# Generated by Django 5.2.6 on 2025-09-12 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('appointement', 'user')},
        ),
    ]
