# Generated by Django 5.1.4 on 2025-08-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_queuegroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuegroup',
            old_name='organisation_id',
            new_name='organisation',
        ),
    ]
