# Generated by Django 5.2.6 on 2025-09-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.TextField(blank=True, null=True, verbose_name='event'),
        ),
    ]
