# Generated by Django 5.1.4 on 2025-08-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_rename_organisation_id_queuegroup_organisation'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuegroup',
            name='organisation',
        ),
        migrations.AddField(
            model_name='queuegroup',
            name='organisation',
            field=models.ManyToManyField(to='organisations.organisation'),
        ),
    ]
