# Generated by Django 5.2.6 on 2025-09-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_message_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='message_type',
            new_name='communication_method',
        ),
    ]
