# Generated by Django 5.2.6 on 2025-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_rename_message_type_participant_communication_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='display_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
