# Generated by Django 5.1.4 on 2025-08-16 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_remove_queuegroup_organisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='consultation_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_beneficiary',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user_id',
        ),
        migrations.AddField(
            model_name='consultation',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('end_expected_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='appointement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment'),
            preserve_default=False,
        ),
    ]
