# Generated by Django 5.1.4 on 2025-08-16 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_remove_consultation_scheduled_date_and_more'),
        ('organisations', '0002_alter_organisation_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueueGroup',
            new_name='Group',
        ),
        migrations.AddField(
            model_name='consultation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.group'),
        ),
    ]
