# Generated by Django 5.2.6 on 2025-09-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_participant_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_auth_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='auth_token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
