# Generated by Django 5.2.6 on 2025-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_participant_is_auth_token_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='verification_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
