# Generated by Django 5.2.6 on 2025-09-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_participant_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='assignment_method',
            field=models.CharField(choices=[('User', 'User'), ('Queue', 'Queue'), ('Appointment', 'Appointment'), ('Manual', 'Manual')], default='Appointment'),
        ),
    ]
