# Generated by Django 5.1.4 on 2025-08-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_alter_message_options_remove_message_particiant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async sending', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='task_logs',
            field=models.TextField(blank=True, help_text='Logs from the sending task'),
        ),
        migrations.AddField(
            model_name='message',
            name='task_traceback',
            field=models.TextField(blank=True, help_text='Error traceback if task failed'),
        ),
    ]
