# Generated by Django 5.2.6 on 2025-09-15 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_alter_reason_assignment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('prescribed_at', models.DateTimeField(blank=True, null=True, verbose_name='prescribed at')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Prescribed', 'Prescribed'), ('Dispensed', 'Dispensed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20, verbose_name='status')),
                ('medication_name', models.CharField(max_length=200, verbose_name='medication name')),
                ('dosage', models.CharField(max_length=100, verbose_name='dosage')),
                ('frequency', models.CharField(max_length=100, verbose_name='frequency')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='duration')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='instructions')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation', verbose_name='consultation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
