# Generated by Django 5.2.6 on 2025-09-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at'], 'permissions': [('assignee_view_consultation', 'Can view assigned consultations'), ('assignee_change_consultation', 'Can change assigned consultations'), ('assignee_delete_consultation', 'Can delete assigned consultations'), ('assignee_close_consultation', 'Can close assigned consultations')], 'verbose_name': 'consultation', 'verbose_name_plural': 'consultations'},
        ),
    ]
