# Generated by Django 5.2.5 on 2025-08-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_alter_consultation_beneficiary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='celery_task_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='external_message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='message',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_phone',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='message',
            name='task_logs',
        ),
        migrations.RemoveField(
            model_name='message',
            name='task_traceback',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(default=None, upload_to='messages_attachment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.participant'),
        ),
    ]
