# Generated by Django 5.2.6 on 2025-09-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_alter_consultation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at'], 'permissions': [('assignee_view_consultation', 'Can view own assigned consultations'), ('assignee_change_consultation', 'Can change own assigned consultations'), ('assignee_delete_consultation', 'Can delete own assigned consultations'), ('assignee_close_consultation', 'Can close own assigned consultations')], 'verbose_name': 'consultation', 'verbose_name_plural': 'consultations'},
        ),
    ]
