# Generated by Django 5.2.6 on 2025-09-16 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_alter_consultation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='appointement',
            new_name='appointment',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('appointment', 'user')},
        ),
    ]
