# Generated by Django 5.2.6 on 2025-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0013_rename_appointement_participant_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_in_consultation',
            field=models.BooleanField(default=False),
        ),
    ]
