# Generated by Django 5.2.5 on 2025-08-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0013_alter_message_attachment_alter_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_by',
            new_name='created_by',
        ),
    ]
