# Generated by Django 5.2.5 on 2025-08-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0014_rename_sent_by_message_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultations.consultation'),
        ),
    ]
