# Generated by Django 5.2.6 on 2025-09-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0014_participant_is_in_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_auth_token_used',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_in_consultation',
        ),
    ]
