# Generated by Django 5.2.6 on 2025-09-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0015_remove_participant_auth_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='verification_code',
        ),
    ]
