# Generated by Django 5.2.5 on 2025-08-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0017_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled'),
        ),
    ]
