# Generated by Django 5.2.6 on 2025-12-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0017_participant_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Draft', verbose_name='status'),
        ),
    ]
