# Generated by Django 5.2.6 on 2025-12-24 13:18

import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0018_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messages_attachment', validators=[django_clamd.validators.validate_file_infection], verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='assignment_method',
            field=models.CharField(choices=[('appointment', ''), ('queue', ''), ('user', '')]),
        ),
    ]
