# Generated by Django 5.2.5 on 2025-08-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0018_appointment_status'),
        ('users', '0003_rename_specialites_user_specialities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='users.speciality'),
        ),
    ]
