# Generated by Django 5.2.5 on 2025-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0019_alter_reason_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
