# Generated by Django 5.2.9 on 2025-12-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0019_alter_message_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='assignment_method',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('queue', 'Queue'), ('user', 'User')]),
        ),
    ]
