# Generated by Django 5.2.9 on 2025-12-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0020_alter_reason_assignment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='consultations.appointment'),
        ),
    ]
