# Generated by Django 5.2.9 on 2025-12-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0021_alter_participant_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
