# Generated by Django 5.2.5 on 2025-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0021_request_consultation_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='requested_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('ACCEPTED', 'Accepted'), ('Cancelled', 'Cancelled')], default='Requested'),
        ),
    ]
