# Generated by Django 5.2.9 on 2025-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0022_participant_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], help_text='Preferred language for the user interface', max_length=10, null=True),
        ),
    ]
