# Generated by Django 5.2.5 on 2025-08-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0023_request_expected_with_alter_consultation_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='request',
        ),
        migrations.AddField(
            model_name='request',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.appointment'),
        ),
        migrations.AddField(
            model_name='request',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation'),
        ),
    ]
