# Generated by Django 5.2.9 on 2025-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0023_participant_preferred_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='display_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
