# Generated by Django 5.2.9 on 2025-12-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0024_rename_display_name_participant_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
