# Generated by Django 5.2.5 on 2025-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0025_slot_consultation_description_consultation_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='token',
            new_name='auth_token',
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='message_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
