# Generated by Django 5.2.9 on 2025-12-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0026_message_is_edited_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='previous_scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='scheduled at'),
        ),
    ]
