# Generated by Django 5.2.5 on 2025-08-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0026_rename_token_participant_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('InPerson', 'In person')], default='Online'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Requested'),
        ),
    ]
