# Generated by Django 5.2.9 on 2026-01-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0028_message_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='is_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
