# Generated by Django 5.2.9 on 2026-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0029_alter_participant_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='draft', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('refused', 'Refused')], default='requested'),
        ),
    ]
