# Generated by Django 5.2.5 on 2025-08-27 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0030_bookingslot_created_by_request_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='end_break',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='start_break',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
