# Generated by Django 5.2.9 on 2026-01-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0030_alter_appointment_status_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('online', 'Online'), ('inPerson', 'In person')], default='online'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('prescribed', 'Prescribed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('online', 'Online'), ('inPerson', 'In person')], default='online'),
        ),
    ]
