# Generated by Django 5.2.5 on 2025-08-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0031_alter_bookingslot_end_break_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Slot valid until this date', null=True),
        ),
    ]
