# Generated by Django 5.2.9 on 2026-01-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0031_participant_is_active_alter_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='communication_method',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], max_length=20, null=True),
        ),
    ]
