# Generated by Django 5.2.9 on 2026-01-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0032_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_at'], 'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='communication_method',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='timezone',
        ),
    ]
