# Generated by Django 5.2.5 on 2025-08-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0032_alter_bookingslot_valid_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingslot',
            old_name='thurday',
            new_name='thursday',
        ),
    ]
