# Generated by Django 5.2.5 on 2025-08-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0033_rename_thurday_bookingslot_thursday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultations.consultation'),
        ),
    ]
