# Generated by Django 5.2.9 on 2026-01-26 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0034_alter_participant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'appointment')},
        ),
    ]
