# Generated by Django 5.2.5 on 2025-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0034_alter_appointment_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
