# Generated by Django 5.2.5 on 2025-08-29 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0035_participant_is_confirmed'),
        ('organisations', '0002_alter_organisation_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Queue',
        ),
        migrations.RenameField(
            model_name='reason',
            old_name='group_assignee',
            new_name='queue_assignee',
        ),
    ]
