# Generated by Django 5.2.10 on 2026-02-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0035_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recording_url',
            field=models.CharField(blank=True, help_text='S3 key/path for call recordings', max_length=500, null=True, verbose_name='recording S3 key'),
        ),
        migrations.CreateModel(
            name='AppointmentRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egress_id', models.CharField(max_length=255, unique=True, verbose_name='egress ID')),
                ('filepath', models.CharField(help_text='S3 key set at recording start', max_length=500, verbose_name='S3 filepath')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='stopped at')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='consultations.appointment', verbose_name='appointment')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording', to='consultations.message', verbose_name='message')),
            ],
            options={
                'verbose_name': 'appointment recording',
                'verbose_name_plural': 'appointment recordings',
                'ordering': ['-started_at'],
            },
        ),
    ]
