# Generated by Django 5.2.5 on 2025-08-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0036_rename_group_queue_and_more'),
        ('organisations', '0002_alter_organisation_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='organisation',
            field=models.ManyToManyField(blank=True, to='organisations.organisation'),
        ),
    ]
