# Generated by Django 5.2.10 on 2026-02-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0037_alter_message_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at'], 'verbose_name': 'consultation', 'verbose_name_plural': 'consultations'},
        ),
    ]
