# Generated by Django 5.2.5 on 2025-08-29 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0037_alter_queue_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='end_break',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), null=True),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='start_break',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
    ]
