# Generated by Django 5.2.5 on 2025-08-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0038_alter_bookingslot_end_break_and_more'),
        ('users', '0011_organisation_alter_user_main_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='organisation',
            field=models.ManyToManyField(blank=True, to='users.organisation'),
        ),
    ]
