# Generated by Django 5.2.10 on 2026-02-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0038_alter_consultation_options'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('date', 'Date'), ('number', 'Number'), ('list', 'List')], max_length=20, verbose_name='type')),
                ('target_model', models.CharField(choices=[('users.HealthMetric', 'Health Metric'), ('consultations.Request', 'Request'), ('consultations.Consultation', 'Consultation'), ('users.User', 'Patient')], max_length=50, verbose_name='target model')),
                ('options', models.JSONField(blank=True, help_text="List of options for 'list' type", null=True, verbose_name='options')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
            ],
            options={
                'verbose_name': 'custom field',
                'verbose_name_plural': 'custom fields',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='consultations.customfield')),
            ],
            options={
                'verbose_name': 'custom field value',
                'verbose_name_plural': 'custom field values',
                'unique_together': {('custom_field', 'content_type', 'object_id')},
            },
        ),
    ]
