# Generated by Django 5.2.10 on 2026-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0039_customfield_customfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
