# Generated by Django 5.2.5 on 2025-09-02 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0039_alter_queue_organisation'),
        ('users', '0016_alter_speciality_options_alter_speciality_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'consultation', 'verbose_name_plural': 'consultations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'queue', 'verbose_name_plural': 'queues'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'verbose_name': 'reason', 'verbose_name_plural': 'reasons'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultations.consultation', verbose_name='consultation'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_expected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end expected at'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(verbose_name='scheduled at'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='beneficiary'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='closed at'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.queue', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='owned by'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='title',
            field=models.CharField(blank=True, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messages_attachment', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultation', verbose_name='consultation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='organisation',
            field=models.ManyToManyField(blank=True, to='users.organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name',
            field=models.CharField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='queue_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.queue', verbose_name='queue assignee'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='users.speciality', verbose_name='speciality'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='user_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user assignee'),
        ),
    ]
