# Generated by Django 5.2.5 on 2025-09-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0040_alter_appointment_options_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('InPerson', 'In person')], default='Online'),
        ),
    ]
