# Generated by Django 5.2.5 on 2025-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0041_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('InPerson', 'In person')], default='Online'),
        ),
    ]
