# Generated by Django 5.2.5 on 2025-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0042_remove_consultation_type_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='refused_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Refused', 'Refused')], default='Requested'),
        ),
    ]
