# Generated by Django 5.2.5 on 2025-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0043_request_refused_reason_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='assignment_method',
            field=models.CharField(choices=[('User', 'User'), ('Queue', 'Queue'), ('Appointement', 'Appointement')], default='Appointement'),
        ),
    ]
