# Generated by Django 5.2.5 on 2025-09-02 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0044_reason_assignment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='consultations.consultation'),
        ),
    ]
