# Generated by Django 5.2.5 on 2025-09-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0045_alter_request_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='assignment_method',
            field=models.CharField(choices=[('User', 'User'), ('Queue', 'Queue'), ('Appointment', 'Appointment')], default='Appointment'),
        ),
    ]
