# Generated by Django 5.2.5 on 2025-09-02 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0046_alter_reason_assignment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasons', to='consultations.reason'),
        ),
    ]
