# Generated by Django 5.2.5 on 2025-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0047_alter_request_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='expected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
