# Generated by Django 5.2.11 on 2026-04-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0047_add_room_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrecording',
            name='mode',
            field=models.CharField(choices=[('screen_recording', 'Screen Recording'), ('transcript', 'Transcript')], default='screen_recording', max_length=20, verbose_name='recording mode'),
        ),
        migrations.AddField(
            model_name='appointmentrecording',
            name='transcript_text',
            field=models.TextField(blank=True, null=True, verbose_name='transcript text'),
        ),
    ]
