# Generated by Django 5.2.11 on 2026-04-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0048_appointmentrecording_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='transcript',
            field=models.TextField(blank=True, help_text='JSON array of transcript lines with timestamps and speakers', null=True, verbose_name='transcript'),
        ),
    ]
