# Generated by Django 5.2.5 on 2025-09-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0048_alter_request_expected_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at'], 'verbose_name': 'consultation', 'verbose_name_plural': 'consultations'},
        ),
    ]
