# Generated by Django 5.2.11 on 2026-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0049_appointment_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='skip_doctor_selection',
            field=models.BooleanField(default=False, help_text='Do not allow the patient to select a practitioner', verbose_name='skip doctor selection'),
        ),
    ]
