# Generated by Django 5.2.11 on 2026-04-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0050_skip_doctor_selection'),
        ('users', '0035_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='users.speciality', verbose_name='speciality'),
        ),
    ]
