# Generated by Django 5.2.11 on 2026-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0052_alter_customfield_target_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='target_model',
            field=models.CharField(choices=[('users.HealthMetric', 'Health Metric'), ('consultations.Request', 'Request'), ('consultations.Consultation', 'Consultation'), ('users.User', 'Patient'), ('users.Practitioner', 'Practitioner'), ('users.Organisation', 'Organisation')], max_length=50, verbose_name='target model'),
        ),
    ]
