# Generated by Django 5.2.6 on 2025-09-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_squashed_0052_alter_queue_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='appointement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='message_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], max_length=20),
        ),
    ]
