# Generated by Django 5.2.11 on 2026-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0054_appointment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='assignment_method',
            field=models.CharField(choices=[('appointment', 'Lookup doctor from speciality, create follow and appointment based on slot'), ('queue', 'Create followup and assign to queue / group'), ('user', 'Create followup and assign to user')]),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name',
            field=models.CharField(help_text='Display name of the reason visible to the patient', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name_de',
            field=models.CharField(help_text='Display name of the reason visible to the patient', null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name_en',
            field=models.CharField(help_text='Display name of the reason visible to the patient', null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name_es',
            field=models.CharField(help_text='Display name of the reason visible to the patient', null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name_fr',
            field=models.CharField(help_text='Display name of the reason visible to the patient', null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='name_it',
            field=models.CharField(help_text='Display name of the reason visible to the patient', null=True, verbose_name='name'),
        ),
    ]
