# Generated by Django 5.2.11 on 2026-04-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0056_consultation_fhir_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultation',
            name='cons_benef_created_idx',
        ),
        migrations.AddField(
            model_name='customfield',
            name='reason',
            field=models.ForeignKey(blank=True, help_text='Reason this field is attached to (asked at booking validation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='consultations.reason', verbose_name='reason'),
        ),
    ]
