# Generated by Django 5.2.11 on 2026-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0059_consultation_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_consultation_visible',
            field=models.BooleanField(default=False, help_text='Grants access to the chat and shared consultation features.', verbose_name='visible in consultation'),
        ),
        migrations.AlterField(
            model_name='queuemembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
    ]
