# Generated by Django 5.2.11 on 2026-05-07 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0060_participant_is_consultation_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='beneficiary_pubkey_fingerprint',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='created_by_pubkey_fingerprint',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='encrypted_key_for_beneficiary',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='encrypted_key_for_created_by',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='encrypted_key_for_master',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='encrypted_key_for_owned_by',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='encrypted_key_for_queue',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='owned_by_pubkey_fingerprint',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='queue_pubkey_fingerprint',
        ),
        migrations.AddField(
            model_name='consultation',
            name='encrypted_private_key_master',
            field=models.TextField(blank=True, help_text='Consultation private key wrapped (envelope) with the platform master pubkey for admin recovery.', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='encrypted_sym_key',
            field=models.TextField(blank=True, help_text='AES sym_key wrapped with the consultation public key.', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='public_key_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='ConsultationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_private_key', models.TextField(verbose_name='encrypted private key')),
                ('pubkey_fingerprint', models.CharField(max_length=64, verbose_name='pubkey fingerprint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='consultations.consultation', verbose_name='consultation')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_keys', to='consultations.queue', verbose_name='queue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_keys', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'consultation key',
                'verbose_name_plural': 'consultation keys',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('queue__isnull', True), ('user__isnull', False)), models.Q(('queue__isnull', False), ('user__isnull', True)), _connector='OR'), name='consultation_key_user_xor_queue'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('consultation', 'user'), name='consultation_key_unique_user'), models.UniqueConstraint(condition=models.Q(('queue__isnull', False)), fields=('consultation', 'queue'), name='consultation_key_unique_queue')],
            },
        ),
    ]
