# Generated by Django 5.2.11 on 2026-05-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0061_remove_consultation_beneficiary_pubkey_fingerprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='encrypted_sym_key',
        ),
    ]
