# Generated by Django 5.2.11 on 2026-05-08 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0062_remove_consultation_encrypted_sym_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuemembership',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_practitioner': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
