# Generated by Django 5.2.11 on 2026-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0064_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='queue',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='reason',
            name='name_uk',
            field=models.CharField(help_text='Display name of the reason visible to the patient', null=True, verbose_name='name'),
        ),
    ]
