# Generated by Django 5.2.11 on 2026-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0064_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When enabled, this field value is exposed on the public practitioner profile', verbose_name='public'),
        ),
    ]
