# Generated by Django 5.2.11 on 2026-06-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0065_customfield_is_public'),
        ('consultations', '0065_customfield_name_uk_queue_name_uk_reason_name_uk'),
    ]

    operations = [
    ]
