# Generated by Django 5.2.11 on 2026-06-25 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0066_merge_20260609_0705'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='is recurring')),
                ('recurrence_interval', models.PositiveIntegerField(default=1, verbose_name='recurrence interval')),
                ('recurrence_period', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='', max_length=10, verbose_name='recurrence period')),
                ('recurrence_count', models.PositiveIntegerField(default=1, verbose_name='recurrence count')),
                ('occurrences_sent', models.PositiveIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='consultatio_is_acti_22cbbd_idx')],
            },
        ),
    ]
