# Generated by Django 5.2.11 on 2026-06-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0067_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='consultations.consultation', verbose_name='consultation'),
        ),
    ]
