# Generated by Django 5.2.11 on 2026-06-25 13:37

from django.conf import settings
from django.db import migrations, models


def backfill_recurrence_end_at(apps, schema_editor):
    """Populate recurrence_end_at for existing reminders using the model logic."""
    from consultations.models import Reminder

    for reminder in Reminder.objects.all():
        reminder.recurrence_end_at = reminder.compute_recurrence_end_at()
        reminder.save(update_fields=["recurrence_end_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0068_reminder_consultation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='recurrence_end_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['scheduled_at', 'recurrence_end_at'], name='consultatio_schedul_253c9d_idx'),
        ),
        migrations.RunPython(
            backfill_recurrence_end_at, migrations.RunPython.noop
        ),
    ]
