# Generated by Django 5.2.11 on 2026-08-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0071_appointment_scheduled_at_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='First time this participant actually joined the call.', null=True, verbose_name='arrived at'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('noshow', 'No show'), ('cancelled', 'Cancelled')], default='scheduled', verbose_name='status'),
        ),
    ]
