# Generated by Django 5.2.11 on 2026-08-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0072_participant_arrived_at_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='queue',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='reason',
            name='name_ar',
            field=models.CharField(help_text='Display name of the reason visible to the patient', null=True, verbose_name='name'),
        ),
    ]
