# Generated by Django 5.1.4 on 2025-08-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('token', models.CharField()),
                ('max_session_number', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
