# Generated by Django 5.2.6 on 2025-09-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('api_secret', models.CharField(verbose_name='API secret')),
                ('max_session_number', models.IntegerField(default=10, verbose_name='max session number')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, null=True, verbose_name='login')),
                ('credential', models.CharField(blank=True, null=True, verbose_name='credential')),
            ],
            options={
                'verbose_name': 'TURN server',
                'verbose_name_plural': 'TURN servers',
            },
        ),
        migrations.CreateModel(
            name='TurnURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='TURN URL (e.g., turn://example.com)', verbose_name='URL')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaserver.turn', verbose_name='TURN server')),
            ],
            options={
                'verbose_name': 'TURN URL',
                'verbose_name_plural': 'TURN URLs',
            },
        ),
    ]
