# Generated by Django 5.2.6 on 2025-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.CharField(choices=[], default='janus'),
            preserve_default=False,
        ),
    ]
