# Generated by Django 5.1.4 on 2025-08-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='token',
            new_name='api_secret',
        ),
    ]
