# Generated by Django 5.2.6 on 2025-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0002_server_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='type',
            field=models.CharField(choices=[('livekit', 'LiveKit')]),
        ),
    ]
