# Generated by Django 5.2.5 on 2025-08-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0002_rename_token_server_api_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaserver.server')),
            ],
        ),
        migrations.CreateModel(
            name='TurnURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='turn:// or ')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaserver.turn')),
            ],
        ),
    ]
