# Generated by Django 5.2.6 on 2025-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0003_alter_server_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='api_token',
            field=models.CharField(blank=True, null=True, verbose_name='API token'),
        ),
        migrations.AlterField(
            model_name='server',
            name='api_secret',
            field=models.CharField(blank=True, null=True, verbose_name='API secret'),
        ),
    ]
