# Generated by Django 5.2.5 on 2025-08-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0003_turn_turnurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='server',
        ),
    ]
