# Generated by Django 5.2.11 on 2026-05-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0004_server_api_token_alter_server_api_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='type',
            field=models.CharField(choices=[('livekit', 'LiveKit'), ('mediasoup', 'MediaSoup')]),
        ),
    ]
