# Generated by Django 5.2.5 on 2025-08-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0004_remove_turn_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='password',
            new_name='credential',
        ),
    ]
