# Generated by Django 5.2.5 on 2025-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0005_rename_password_turn_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnurl',
            name='url',
            field=models.CharField(help_text='turn:// or '),
        ),
    ]
