# Generated by Django 5.2.5 on 2025-09-02 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0006_alter_turnurl_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'server', 'verbose_name_plural': 'servers'},
        ),
        migrations.AlterModelOptions(
            name='turn',
            options={'verbose_name': 'TURN server', 'verbose_name_plural': 'TURN servers'},
        ),
        migrations.AlterModelOptions(
            name='turnurl',
            options={'verbose_name': 'TURN URL', 'verbose_name_plural': 'TURN URLs'},
        ),
        migrations.AlterField(
            model_name='server',
            name='api_secret',
            field=models.CharField(verbose_name='API secret'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='server',
            name='max_session_number',
            field=models.IntegerField(default=10, verbose_name='max session number'),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='credential',
            field=models.CharField(blank=True, null=True, verbose_name='credential'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='login',
            field=models.CharField(blank=True, null=True, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='turnurl',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaserver.turn', verbose_name='TURN server'),
        ),
        migrations.AlterField(
            model_name='turnurl',
            name='url',
            field=models.CharField(help_text='TURN URL (e.g., turn://example.com)', verbose_name='URL'),
        ),
    ]
