# Generated by Django 5.1.4 on 2025-08-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this a default system configuration'),
        ),
    ]
