# Generated by Django 5.1.4 on 2025-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
