# Generated by Django 5.2.5 on 2025-08-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0039_alter_queue_organisation'),
        ('organisations', '0002_alter_organisation_primary_color'),
        ('users', '0011_organisation_alter_user_main_organisation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
