# Generated by Django 5.2.10 on 2026-02-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('patient', 'Patient'), ('practitioner', 'Practitioner')], max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'ordering': ['component', 'language', 'key'],
                'unique_together': {('component', 'language', 'key')},
            },
        ),
    ]
