# Generated by Django 5.1.4 on 2025-08-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessagingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Swisscom', 'Swisscom'), ('Ovh', 'Ovh'), ('ClickATel', 'ClickATel'), ('Twilio', 'Twilio'), ('Twilio Whatsapp', 'Twilio Whatsapp')], max_length=20)),
                ('api_key', models.CharField(max_length=200)),
                ('source_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=50, null=True)),
                ('account_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.ManyToManyField(blank=True, to='messaging.prefix')),
            ],
        ),
    ]
