# Generated by Django 5.1.4 on 2025-08-15 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagingprovider',
            name='prefix',
        ),
        migrations.AddField(
            model_name='prefix',
            name='messaging_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.messagingprovider'),
        ),
    ]
