# Generated by Django 5.2.6 on 2025-09-11 09:09

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingprovider',
            name='communication_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], default='SMS', verbose_name=messaging.models.CommunicationMethod),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='name',
            field=models.CharField(choices=[('ovh', 'Ovh SMS')], max_length=20, verbose_name='name'),
        ),
    ]
