# Generated by Django 5.1.4 on 2025-08-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_messagingprovider_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingprovider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
