# Generated by Django 5.1.4 on 2025-08-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagingprovider_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name_plural': 'prefixes'},
        ),
    ]
