# Generated by Django 5.2.6 on 2025-09-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagingprovider_communication_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingprovider',
            name='communication_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')]),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='name',
            field=models.CharField(choices=[('email', 'Email over Django SMTP'), ('ovh', 'Ovh SMS'), ('swisscom', 'Swisscom SMS'), ('twilio_sms', 'Twilio SMS')], max_length=20, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='messagingprovider',
            unique_together={('communication_method', 'priority')},
        ),
    ]
