# Generated by Django 5.1.4 on 2025-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_prefix_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingprovider',
            name='name',
            field=models.CharField(choices=[('Swisscom', 'Swisscom'), ('Ovh', 'Ovh'), ('ClickATel', 'ClickATel'), ('Twilio', 'Twilio'), ('Twilio Whatsapp', 'Twilio Whatsapp'), ('EMAIL', 'Email')], max_length=20),
        ),
    ]
