# Generated by Django 5.2.6 on 2025-09-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_messagingprovider_communication_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingprovider',
            name='application_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='application key'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='application_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='application secret'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='client_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='client ID'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='client_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='client secret'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='consumer_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='consumer key'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='from email'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='from_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='from phone'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='sender_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sender ID'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='service name'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='account_sid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='account SID'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='auth_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='auth token'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='name',
            field=models.CharField(choices=[('clickatel', 'Clickatel SMS'), ('email', 'Email over Django SMTP'), ('ovh', 'Ovh SMS'), ('swisscom', 'Swisscom SMS'), ('twilio_sms', 'Twilio SMS'), ('twilio_whatsapp', 'Twilio WhatsApp')], max_length=20, verbose_name='name'),
        ),
    ]
