# Generated by Django 5.2.6 on 2025-09-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_messagingprovider_application_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagingprovider',
            name='source_phone',
        ),
    ]
