# Generated by Django 5.2.5 on 2025-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.AddField(
            model_name='message',
            name='communication_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], default='sms', max_length=20),
        ),
    ]
