# Generated by Django 5.2.6 on 2025-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_messagingprovider_source_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='system name')),
                ('name', models.CharField(help_text='Human-readable template name', max_length=200, verbose_name='name')),
                ('name_en', models.CharField(help_text='Human-readable template name', max_length=200, null=True, verbose_name='name')),
                ('name_de', models.CharField(help_text='Human-readable template name', max_length=200, null=True, verbose_name='name')),
                ('name_fr', models.CharField(help_text='Human-readable template name', max_length=200, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of the template purpose', verbose_name='description')),
                ('description_en', models.TextField(blank=True, help_text='Description of the template purpose', null=True, verbose_name='description')),
                ('description_de', models.TextField(blank=True, help_text='Description of the template purpose', null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, help_text='Description of the template purpose', null=True, verbose_name='description')),
                ('template_text', models.TextField(help_text='Jinja2 template for message content', verbose_name='template text')),
                ('template_text_en', models.TextField(help_text='Jinja2 template for message content', null=True, verbose_name='template text')),
                ('template_text_de', models.TextField(help_text='Jinja2 template for message content', null=True, verbose_name='template text')),
                ('template_text_fr', models.TextField(help_text='Jinja2 template for message content', null=True, verbose_name='template text')),
                ('template_subject', models.CharField(blank=True, help_text='Jinja2 template for message subject', max_length=500, verbose_name='template subject')),
                ('template_subject_en', models.CharField(blank=True, help_text='Jinja2 template for message subject', max_length=500, null=True, verbose_name='template subject')),
                ('template_subject_de', models.CharField(blank=True, help_text='Jinja2 template for message subject', max_length=500, null=True, verbose_name='template subject')),
                ('template_subject_fr', models.CharField(blank=True, help_text='Jinja2 template for message subject', max_length=500, null=True, verbose_name='template subject')),
                ('communication_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], max_length=20, verbose_name='communication method')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ['name'],
            },
        ),
    ]
