# Generated by Django 5.2.6 on 2025-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='communication_method',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], max_length=20, verbose_name='communication method'),
        ),
    ]
