# Generated by Django 5.2.5 on 2025-09-02 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_message_sent_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagingprovider',
            options={'verbose_name': 'messaging provider', 'verbose_name_plural': 'messaging providers'},
        ),
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name': 'prefix', 'verbose_name_plural': 'prefixes'},
        ),
        migrations.AlterField(
            model_name='message',
            name='communication_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], default='sms', max_length=20, verbose_name='communication method'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='provider_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='provider name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='recipient email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='recipient phone'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='account_sid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='account SID'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='api_key',
            field=models.CharField(max_length=200, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='auth_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='auth token'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='name',
            field=models.CharField(choices=[('Swisscom', 'Swisscom'), ('Ovh', 'Ovh'), ('ClickATel', 'ClickATel'), ('Twilio', 'Twilio'), ('Twilio Whatsapp', 'Twilio Whatsapp'), ('EMAIL', 'Email')], max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='source_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='source phone'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='messaging_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.messagingprovider', verbose_name='messaging provider'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='start_by',
            field=models.CharField(max_length=50, verbose_name='start by'),
        ),
    ]
