# Generated by Django 5.2.6 on 2025-09-13 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_template_communication_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='communication_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], max_length=10), blank=True, default=list, size=None),
        ),
    ]
