# Generated by Django 5.2.6 on 2025-09-15 13:00

from django.db import migrations, models

import messaging.models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0009_alter_template_communication_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="model",
            field=models.CharField(
                choices=messaging.models.get_model_choices, default=None, max_length=100
            ),
            preserve_default=False,
        ),
    ]
