# Generated by Django 5.2.6 on 2025-09-15 14:31

import django.db.models.deletion
from django.db import migrations, models

import messaging.models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0010_template_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="model",
            field=models.CharField(
                choices=messaging.models.get_model_choices,
                help_text="This model will be required to contruct message.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_text",
            field=models.TextField(
                help_text="Jinja2 template for message content, use {{ obj }} to get object attributes",
                verbose_name="template text",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_text_de",
            field=models.TextField(
                help_text="Jinja2 template for message content, use {{ obj }} to get object attributes",
                null=True,
                verbose_name="template text",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_text_en",
            field=models.TextField(
                help_text="Jinja2 template for message content, use {{ obj }} to get object attributes",
                null=True,
                verbose_name="template text",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_text_fr",
            field=models.TextField(
                help_text="Jinja2 template for message content, use {{ obj }} to get object attributes",
                null=True,
                verbose_name="template text",
            ),
        ),
        migrations.CreateModel(
            name="TemplateValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_template_id",
                    models.CharField(
                        help_text="External template ID from the messaging provider",
                        max_length=200,
                        verbose_name="external template ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("validated", "Validated"),
                            ("rejected", "Rejected"),
                        ],
                        default="created",
                        help_text="Current validation status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the template was validated",
                        null=True,
                    ),
                ),
                (
                    "validation_response",
                    models.JSONField(
                        blank=True,
                        help_text="Response from the messaging provider during validation",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if validation failed"
                    ),
                ),
                (
                    "messaging_provider",
                    models.ForeignKey(
                        help_text="The messaging provider where the template is validated",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.messagingprovider",
                        verbose_name="messaging provider",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The local template that needs validation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.template",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "template validation",
                "verbose_name_plural": "template validations",
                "ordering": ["-created_at"],
                "unique_together": {("messaging_provider", "template")},
            },
        ),
    ]
