# Generated by Django 5.2.6 on 2025-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_alter_template_model_alter_template_template_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatevalidation',
            name='external_template_id',
            field=models.CharField(blank=True, help_text='External template ID from the messaging provider (populated after validation submission)', max_length=200, verbose_name='external template ID'),
        ),
    ]
