# Generated by Django 5.2.6 on 2025-09-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_alter_templatevalidation_external_template_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatevalidation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='templatevalidation',
            name='language_code',
            field=models.CharField(default='en', help_text='Language code for the template validation (e.g., "en", "fr", "de")', max_length=5, verbose_name='language code'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='templatevalidation',
            unique_together={('messaging_provider', 'template', 'language_code')},
        ),
    ]
