# Generated by Django 5.2.6 on 2025-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_alter_templatevalidation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatevalidation',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async sending', max_length=255),
        ),
        migrations.AddField(
            model_name='templatevalidation',
            name='task_logs',
            field=models.TextField(blank=True, help_text='Logs from the sending task'),
        ),
        migrations.AddField(
            model_name='templatevalidation',
            name='task_traceback',
            field=models.TextField(blank=True, help_text='Error traceback if task failed'),
        ),
        migrations.AlterField(
            model_name='templatevalidation',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('outdated', 'Outdated'), ('unsued', 'Unused')], default='created', help_text='Current validation status', max_length=20, verbose_name='status'),
        ),
    ]
