# Generated by Django 5.2.6 on 2025-09-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_templatevalidation_celery_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='task_logs',
        ),
        migrations.RemoveField(
            model_name='message',
            name='task_traceback',
        ),
        migrations.RemoveField(
            model_name='templatevalidation',
            name='task_logs',
        ),
        migrations.RemoveField(
            model_name='templatevalidation',
            name='task_traceback',
        ),
    ]
