# Generated by Django 5.2.6 on 2025-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_remove_message_task_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task_logs',
            field=models.TextField(blank=True, help_text='Logs from the sending task'),
        ),
        migrations.AddField(
            model_name='templatevalidation',
            name='task_logs',
            field=models.TextField(blank=True, help_text='Logs from the sending task'),
        ),
    ]
