# Generated by Django 5.2.6 on 2025-09-16 11:28

from django.db import migrations, models

import messaging.models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0016_message_task_logs_templatevalidation_task_logs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatevalidation",
            name="error_message",
        ),
        migrations.AlterField(
            model_name="template",
            name="model",
            field=models.CharField(
                blank=True,
                choices=messaging.models.get_model_choices,
                help_text="This model will be required to contruct message.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="templatevalidation",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("validated", "Validated"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                    ("outdated", "Outdated"),
                    ("unsued", "Unused"),
                ],
                default="created",
                help_text="Current validation status",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
