# Generated by Django 5.2.6 on 2025-09-16 11:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0017_remove_templatevalidation_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingprovider',
            name='excluded_prefixes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Phone prefixes that should NOT use this provider', size=None, verbose_name='excluded prefixes'),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='included_prefixes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Phone prefixes that should use this provider (if empty, all prefixes except excluded ones are allowed)', size=None, verbose_name='included prefixes'),
        ),
    ]
