# Generated by Django 5.2.6 on 2025-09-16 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0018_messagingprovider_excluded_prefixes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingprovider',
            name='excluded_prefixes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Phone prefixes that should NOT use this provider. Separate multiple prefixes with commas (e.g. +33, +41, +1)', size=None, verbose_name='excluded prefixes'),
        ),
        migrations.AlterField(
            model_name='messagingprovider',
            name='included_prefixes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Phone prefixes that should use this provider. Separate multiple prefixes with commas (e.g. +33, +41). If empty, all prefixes except excluded ones are allowed', size=None, verbose_name='included prefixes'),
        ),
        migrations.DeleteModel(
            name='Prefix',
        ),
    ]
