# Generated by Django 5.2.6 on 2025-09-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0019_alter_messagingprovider_excluded_prefixes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='system_name',
        ),
        migrations.AddField(
            model_name='template',
            name='event_type',
            field=models.CharField(choices=[('you_have_been_assigned_to_consultation', 'Message sent to user when assigned to a consultation'), ('an_unprocessed_request_has_been_received', 'Message sent to user when a consultation request requires manual processing'), ('a_message_has_been_sent_by_beneficiary', 'Message sent to user when a beneficiary sends a message'), ('invitation_to_join_consultation_now', 'Message sent to user with invitation to join a consultation immediately'), ('invitation_to_join_consultation_later', 'Message sent to user with invitation to join a consultation at a later time'), ('your_appointment_is_in_24h', 'Message sent to user 24 hours before scheduled appointment'), ('your_authentication_code_is_participant', 'Message sent to participant containing their authentication code')], default=' ', help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='system name'),
            preserve_default=False,
        ),
    ]
