# Generated by Django 5.2.6 on 2025-09-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0020_remove_template_system_name_template_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'template', 'verbose_name_plural': 'templates'},
        ),
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='template',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='template',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='template',
            name='name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='template',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='template',
            name='name_fr',
        ),
    ]
