# Generated by Django 5.2.9 on 2025-12-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0021_alter_template_options_remove_template_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='communication_method',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], max_length=20, null=True, verbose_name='communication method'),
        ),
    ]
