# Generated by Django 5.2.9 on 2025-12-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0023_message_template_alter_message_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='template',
        ),
        migrations.AddField(
            model_name='message',
            name='object_dict',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='template_system_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
