# Generated by Django 5.2.9 on 2025-12-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0024_remove_message_template_message_object_dict_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='template_text',
            new_name='template_content',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='template_text_de',
            new_name='template_content_de',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='template_text_en',
            new_name='template_content_en',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='template_text_fr',
            new_name='template_content_fr',
        ),
        migrations.AlterField(
            model_name='message',
            name='template_system_name',
            field=models.CharField(blank=True, choices=[('you_have_been_assigned_to_consultation', 'Message sent to user when assigned to a consultation'), ('an_unprocessed_request_has_been_received', 'Message sent to user when a consultation request requires manual processing'), ('a_message_has_been_sent_by_beneficiary', 'Message sent to user when a beneficiary sends a message'), ('invitation_to_join_consultation_now', 'Message sent to user with invitation to join a consultation immediately'), ('invitation_to_join_consultation_later', 'Message sent to user with invitation to join a consultation at a later time'), ('your_appointment_is_in_24h', 'Message sent to user 24 hours before scheduled appointment'), ('your_authentication_code_is_participant', 'Message sent to participant containing their authentication code')], null=True),
        ),
    ]
