# Generated by Django 5.2.9 on 2025-12-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0025_rename_template_text_template_template_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='template_system_name',
            field=models.CharField(blank=True, choices=[('you_have_been_assigned_to_consultation', 'Message sent to user when assigned to a consultation'), ('an_unprocessed_request_has_been_received', 'Message sent to user when a consultation request requires manual processing'), ('a_message_has_been_sent_by_beneficiary', 'Message sent to user when a beneficiary sends a message'), ('invitation_to_appointment', 'Message sent to user with invitation to join a consultation at a later time'), ('your_appointment_is_in_24h', 'Message sent to user 24 hours before scheduled appointment'), ('your_authentication_code_is_participant', 'Message sent to participant containing their authentication code')], null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='event_type',
            field=models.CharField(choices=[('you_have_been_assigned_to_consultation', 'Message sent to user when assigned to a consultation'), ('an_unprocessed_request_has_been_received', 'Message sent to user when a consultation request requires manual processing'), ('a_message_has_been_sent_by_beneficiary', 'Message sent to user when a beneficiary sends a message'), ('invitation_to_appointment', 'Message sent to user with invitation to join a consultation at a later time'), ('your_appointment_is_in_24h', 'Message sent to user 24 hours before scheduled appointment'), ('your_authentication_code_is_participant', 'Message sent to participant containing their authentication code')], help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='system name'),
        ),
    ]
