# Generated by Django 5.2.9 on 2025-12-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0026_alter_message_template_system_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
