# Generated by Django 5.2.9 on 2025-12-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0027_alter_message_error_message_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='recipient email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='recipient phone'),
        ),
    ]
