# Generated by Django 5.2.9 on 2025-12-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0028_alter_message_recipient_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='object_dict',
        ),
        migrations.AddField(
            model_name='message',
            name='object_model',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='object_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
