# Generated by Django 5.2.9 on 2025-12-29 09:15

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0029_remove_message_object_dict_message_object_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='object_model',
            field=models.CharField(blank=True, choices=messaging.models.get_model_choices, null=True),
        ),
    ]
