# Generated by Django 5.2.9 on 2025-12-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0030_alter_message_object_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='model',
        ),
    ]
