# Generated by Django 5.2.9 on 2026-01-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0034_alter_message_template_system_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='template_system_name',
            field=models.CharField(blank=True, choices=[('appointment_first_reminder', 'Message sent to participant when a beneficiary sends a message'), ('appointment_last_reminder', 'Message sent to participant when a beneficiary sends a message'), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation')], null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='event_type',
            field=models.CharField(choices=[('appointment_first_reminder', 'Message sent to participant when a beneficiary sends a message'), ('appointment_last_reminder', 'Message sent to participant when a beneficiary sends a message'), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation')], help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='system name'),
        ),
    ]
