# Generated by Django 5.2.9 on 2026-01-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0035_alter_message_template_system_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_html',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_content_html',
            field=models.TextField(blank=True, help_text='Jinja2 template for message content in html, use {{ obj }} to get object attributes', null=True, verbose_name='template html'),
        ),
    ]
