# Generated by Django 5.2.9 on 2026-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0036_message_content_html_template_template_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='action_label',
            field=models.CharField(default='join', help_text='Label display in the action', max_length=100, verbose_name='action label'),
            preserve_default=False,
        ),
    ]
