# Generated by Django 5.2.10 on 2026-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0040_alter_message_template_system_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content_html',
            field=models.TextField(blank=True, null=True, verbose_name='content html'),
        ),
        migrations.AlterField(
            model_name='message',
            name='template_system_name',
            field=models.CharField(blank=True, choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user to verify their email address after registration'), ('reset_password', 'Notification sent user request to change password')], null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='event_type',
            field=models.CharField(choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user to verify their email address after registration'), ('reset_password', 'Notification sent user request to change password')], help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='system name'),
        ),
    ]
