# Generated by Django 5.2.10 on 2026-02-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0041_alter_message_content_alter_message_content_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_content_html_de',
            field=models.TextField(blank=True, help_text='Jinja2 template for message content in html, use {{ obj }} to get object attributes', null=True, verbose_name='template html'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_content_html_en',
            field=models.TextField(blank=True, help_text='Jinja2 template for message content in html, use {{ obj }} to get object attributes', null=True, verbose_name='template html'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_content_html_fr',
            field=models.TextField(blank=True, help_text='Jinja2 template for message content in html, use {{ obj }} to get object attributes', null=True, verbose_name='template html'),
        ),
    ]
