# Generated by Django 5.2.11 on 2026-04-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0051_template_template_content_es_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'template override', 'verbose_name_plural': 'template overrides'},
        ),
    ]
