# Generated by Django 5.2.11 on 2026-05-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0053_ephemeralmessage_alter_message_template_system_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingprovider',
            name='name',
            field=models.CharField(choices=[('clickatel', 'Clickatel SMS'), ('email', 'Email over Django SMTP'), ('ovh', 'OVH SMS'), ('smsmode', 'smsmode SMS'), ('swisscom', 'Swisscom SMS'), ('twilio_sms', 'Twilio SMS'), ('twilio_whatsapp', 'Twilio WhatsApp'), ('webpush', 'Web Push (VAPID)')], max_length=20, verbose_name='name'),
        ),
    ]
