# Generated by Django 5.2.11 on 2026-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0054_alter_messagingprovider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_content_html_uk',
            field=models.TextField(blank=True, help_text='Jinja2 template for message content in html, use {{ obj }} to get object attributes', null=True, verbose_name='template html'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_content_uk',
            field=models.TextField(help_text='Jinja2 template for message content, use {{ obj }} to get object attributes', null=True, verbose_name='template text'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_subject_uk',
            field=models.CharField(blank=True, help_text='Jinja2 template for message subject', max_length=500, null=True, verbose_name='template subject'),
        ),
    ]
