# Generated by Django 6.0.8 on 2026-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0059_email_verification_code_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='template_system_name',
            field=models.CharField(blank=True, choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('invitation_to_ongoing_appointment', 'Message sent to a participant invited while the call is already running'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user containing the code to verify their email address or phone number after registration'), ('reset_password', 'Notification sent user request to change password'), ('consultation_assigned', 'Notification sent to patient when a consultation is assigned to them'), ('encryption_passphrase', 'Sent once to a user when their encryption keypair is provisioned'), ('encryption_passphrase_for_practitioner', "Sent to the practitioner who created a manual-contact patient, carrying the patient's encryption passphrase"), ('reminder', 'Custom reminder scheduled by a practitioner towards a contact')], null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='event_type',
            field=models.CharField(choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('invitation_to_ongoing_appointment', 'Message sent to a participant invited while the call is already running'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user containing the code to verify their email address or phone number after registration'), ('reset_password', 'Notification sent user request to change password'), ('consultation_assigned', 'Notification sent to patient when a consultation is assigned to them'), ('encryption_passphrase', 'Sent once to a user when their encryption keypair is provisioned'), ('encryption_passphrase_for_practitioner', "Sent to the practitioner who created a manual-contact patient, carrying the patient's encryption passphrase"), ('reminder', 'Custom reminder scheduled by a practitioner towards a contact')], help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='system name'),
        ),
        migrations.AlterField(
            model_name='templatevalidation',
            name='event_type',
            field=models.CharField(choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('invitation_to_ongoing_appointment', 'Message sent to a participant invited while the call is already running'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user containing the code to verify their email address or phone number after registration'), ('reset_password', 'Notification sent user request to change password'), ('consultation_assigned', 'Notification sent to patient when a consultation is assigned to them'), ('encryption_passphrase', 'Sent once to a user when their encryption keypair is provisioned'), ('encryption_passphrase_for_practitioner', "Sent to the practitioner who created a manual-contact patient, carrying the patient's encryption passphrase"), ('reminder', 'Custom reminder scheduled by a practitioner towards a contact')], help_text='The template event type to validate', max_length=100, verbose_name='event type'),
        ),
    ]
