import { SelectOption } from '../models/select';

export const states: SelectOption[] = [
  { label: 'Alabama', value: 'AL' },
  { label: 'Alaska', value: 'AK' },
  { label: 'Arizona', value: 'AZ' },
  { label: 'Arkansas', value: 'AR' },
  { label: 'California', value: 'CA' },
  { label: 'Colorado', value: 'CO' },
  { label: 'Connecticut', value: 'CT' },
  { label: 'Delaware', value: 'DE' },
  { label: 'Florida', value: 'FL' },
  { label: 'Georgia', value: 'GA' },
  { label: 'Hawaii', value: 'HI' },
  { label: 'Idaho', value: 'ID' },
  { label: 'Illinois', value: 'IL' },
  { label: 'Indiana', value: 'IN' },
  { label: 'Iowa', value: 'IA' },
  { label: 'Kansas', value: 'KS' },
  { label: 'Kentucky', value: 'KY' },
  { label: 'Louisiana', value: 'LA' },
  { label: 'Maine', value: 'ME' },
  { label: 'Maryland', value: 'MD' },
  { label: 'Massachusetts', value: 'MA' },
  { label: 'Michigan', value: 'MI' },
  { label: 'Minnesota', value: 'MN' },
  { label: 'Mississippi', value: 'MS' },
  { label: 'Missouri', value: 'MO' },
  { label: 'Montana', value: 'MT' },
  { label: 'Nebraska', value: 'NE' },
  { label: 'Nevada', value: 'NV' },
  { label: 'New Hampshire', value: 'NH' },
  { label: 'New Jersey', value: 'NJ' },
  { label: 'New Mexico', value: 'NM' },
  { label: 'New York', value: 'NY' },
  { label: 'North Carolina', value: 'NC' },
  { label: 'North Dakota', value: 'ND' },
  { label: 'Ohio', value: 'OH' },
  { label: 'Oklahoma', value: 'OK' },
  { label: 'Oregon', value: 'OR' },
  { label: 'Pennsylvania', value: 'PA' },
  { label: 'Rhode Island', value: 'RI' },
  { label: 'South Carolina', value: 'SC' },
  { label: 'South Dakota', value: 'SD' },
  { label: 'Tennessee', value: 'TN' },
  { label: 'Texas', value: 'TX' },
  { label: 'Utah', value: 'UT' },
  { label: 'Vermont', value: 'VT' },
  { label: 'Virginia', value: 'VA' },
  { label: 'Washington', value: 'WA' },
  { label: 'West Virginia', value: 'WV' },
  { label: 'Wisconsin', value: 'WI' },
  { label: 'Wyoming', value: 'WY' },
];

export const plateStates: SelectOption[] = [
  { label: 'Alabama', value: 'AL' },
  { label: 'Alaska', value: 'AK' },
  { label: 'Arizona', value: 'AZ' },
  { label: 'Arkansas', value: 'AR' },
  { label: 'California', value: 'CA' },
  { label: 'Colorado', value: 'CO' },
  { label: 'Connecticut', value: 'CT' },
  { label: 'Delaware', value: 'DE' },
  { label: 'Florida', value: 'FL' },
  { label: 'Georgia', value: 'GA' },
  { label: 'Hawaii', value: 'HI' },
  { label: 'Idaho', value: 'ID' },
  { label: 'Illinois', value: 'IL' },
  { label: 'Indiana', value: 'IN' },
  { label: 'Iowa', value: 'IA' },
  { label: 'Kansas', value: 'KS' },
  { label: 'Kentucky', value: 'KY' },
  { label: 'Louisiana', value: 'LA' },
  { label: 'Maine', value: 'ME' },
  { label: 'Maryland', value: 'MD' },
  { label: 'Massachusetts', value: 'MA' },
  { label: 'Michigan', value: 'MI' },
  { label: 'Minnesota', value: 'MN' },
  { label: 'Mississippi', value: 'MS' },
  { label: 'Missouri', value: 'MO' },
  { label: 'Montana', value: 'MT' },
  { label: 'Nebraska', value: 'NE' },
  { label: 'Nevada', value: 'NV' },
  { label: 'New Hampshire', value: 'NH' },
  { label: 'New Jersey', value: 'NJ' },
  { label: 'New Mexico', value: 'NM' },
  { label: 'New York', value: 'NY' },
  { label: 'North Carolina', value: 'NC' },
  { label: 'North Dakota', value: 'ND' },
  { label: 'Ohio', value: 'OH' },
  { label: 'Oklahoma', value: 'OK' },
  { label: 'Oregon', value: 'OR' },
  { label: 'Pennsylvania', value: 'PA' },
  { label: 'Rhode Island', value: 'RI' },
  { label: 'South Carolina', value: 'SC' },
  { label: 'South Dakota', value: 'SD' },
  { label: 'Tennessee', value: 'TN' },
  { label: 'Texas', value: 'TX' },
  { label: 'Utah', value: 'UT' },
  { label: 'Vermont', value: 'VT' },
  { label: 'Virginia', value: 'VA' },
  { label: 'Washington DC', value: 'DC' },
  { label: 'Washington', value: 'WA' },
  { label: 'West Virginia', value: 'WV' },
  { label: 'Wisconsin', value: 'WI' },
  { label: 'Wyoming', value: 'WY' },
];

export const colors: SelectOption[] = [
  { label: 'AliceBlue', value: 'AliceBlue' },
  { label: 'AntiqueWhite', value: 'AntiqueWhite' },
  { label: 'Aqua', value: 'Aqua' },
  { label: 'Coral', value: 'Coral' },
  { label: 'Crimson', value: 'Crimson' },
  { label: 'Gold', value: 'Gold' },
  { label: 'HotPink', value: 'HotPink' },
  { label: 'Indigo', value: 'Indigo' },
  { label: 'Khaki', value: 'Khaki' },
  { label: 'Lavender', value: 'Lavender' },
  { label: 'LimeGreen', value: 'LimeGreen' },
  { label: 'MidnightBlue', value: 'MidnightBlue' },
  { label: 'OliveDrab', value: 'OliveDrab' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Plum', value: 'Plum' },
  { label: 'Salmon', value: 'Salmon' },
  { label: 'SlateGray', value: 'SlateGray' },
  { label: 'Tan', value: 'Tan' },
  { label: 'Tomato', value: 'Tomato' },
  { label: 'Turquoise', value: 'Turquoise' },
  { label: 'Azure', value: 'Azure' },
  { label: 'Beige', value: 'Beige' },
  { label: 'Bisque', value: 'Bisque' },
  { label: 'Black', value: 'Black' },
  { label: 'Blue', value: 'Blue' },
  { label: 'BlueViolet', value: 'BlueViolet' },
  { label: 'Brown', value: 'Brown' },
  { label: 'BurlyWood', value: 'BurlyWood' },
  { label: 'CadetBlue', value: 'CadetBlue' },
  { label: 'Chartreuse', value: 'Chartreuse' },
  { label: 'Chocolate', value: 'Chocolate' },
  { label: 'CornflowerBlue', value: 'CornflowerBlue' },
  { label: 'DarkBlue', value: 'DarkBlue' },
  { label: 'DarkCyan', value: 'DarkCyan' },
  { label: 'DarkGoldenRod', value: 'DarkGoldenRod' },
  { label: 'DarkGreen', value: 'DarkGreen' },
  { label: 'DarkMagenta', value: 'DarkMagenta' },
  { label: 'DarkOrange', value: 'DarkOrange' },
  { label: 'DarkOrchid', value: 'DarkOrchid' },
  { label: 'DeepSkyBlue', value: 'DeepSkyBlue' },
  { label: 'DimGray', value: 'DimGray' },
  { label: 'DodgerBlue', value: 'DodgerBlue' },
  { label: 'ForestGreen', value: 'ForestGreen' },
  { label: 'Fuchsia', value: 'Fuchsia' },
  { label: 'Gainsboro', value: 'Gainsboro' },
  { label: 'GhostWhite', value: 'GhostWhite' },
  { label: 'GreenYellow', value: 'GreenYellow' },
  { label: 'LightBlue', value: 'LightBlue' },
  { label: 'LightCoral', value: 'LightCoral' },
  { label: 'LightGreen', value: 'LightGreen' },
  { label: 'LightSalmon', value: 'LightSalmon' },
  { label: 'LightSeaGreen', value: 'LightSeaGreen' },
  { label: 'Moccasin', value: 'Moccasin' },
  { label: 'Navy', value: 'Navy' },
  { label: 'Orange', value: 'Orange' },
  { label: 'Orchid', value: 'Orchid' },
  { label: 'PaleVioletRed', value: 'PaleVioletRed' },
  { label: 'PeachPuff', value: 'PeachPuff' },
  { label: 'PowderBlue', value: 'PowderBlue' },
  { label: 'RebeccaPurple', value: 'RebeccaPurple' },
  { label: 'RoyalBlue', value: 'RoyalBlue' },
  { label: 'Sienna', value: 'Sienna' },
  { label: 'SkyBlue', value: 'SkyBlue' },
  { label: 'Snow', value: 'Snow' },
  { label: 'SpringGreen', value: 'SpringGreen' },
  { label: 'SteelBlue', value: 'SteelBlue' },
  { label: 'Violet', value: 'Violet' },
  { label: 'Wheat', value: 'Wheat' },
  { label: 'White', value: 'White' },
  { label: 'WhiteSmoke', value: 'WhiteSmoke' },
  { label: 'Yellow', value: 'Yellow' },
  { label: 'YellowGreen', value: 'YellowGreen' },
];

