# Generated by Django 5.2.6 on 2025-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
