# Generated by Django 5.2.5 on 2025-08-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_language_speciality_user_languages_user_specialites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='specialites',
            new_name='specialities',
        ),
    ]
