# Generated by Django 5.2.6 on 2025-09-11 06:53

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='location_longitude',
        ),
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
