# Generated by Django 5.2.5 on 2025-08-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_specialites_user_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='communication_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('manual', 'Manual')], default='email'),
        ),
    ]
