# Generated by Django 5.2.5 on 2025-08-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_communication_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_phone_numer',
            field=models.CharField(blank=True, null=True),
        ),
    ]
