# Generated by Django 5.2.6 on 2025-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_organisation_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_de',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_fr',
            field=models.CharField(null=True),
        ),
    ]
