# Generated by Django 5.2.6 on 2025-09-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_term_content_de_term_content_en_term_content_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='valid_until',
        ),
    ]
