# Generated by Django 5.2.5 on 2025-08-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_languages_alter_user_specialities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, to='users.language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='users.speciality'),
        ),
    ]
