# Generated by Django 5.2.6 on 2025-09-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appointment_auth_token',
            field=models.CharField(blank=True, help_text='Authentication token for appointment access', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='is_appointment_auth_token_used',
            field=models.BooleanField(default=False, help_text='Whether the appointment auth token has been used before'),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary',
            field=models.BooleanField(default=False, help_text='Indicates if this is a temporary user created for appointments'),
        ),
    ]
