# Generated by Django 5.2.5 on 2025-08-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_organisation_primary_color'),
        ('users', '0007_alter_user_languages_alter_user_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='organisations.organisation'),
        ),
    ]
