# Generated by Django 5.2.6 on 2025-11-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title or professional designation', max_length=200, null=True),
        ),
    ]
