# Generated by Django 5.2.5 on 2025-08-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_organisation_primary_color'),
        ('users', '0009_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_mainorganisation', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_perferred_language', to='users.language'),
        ),
    ]
