# Generated by Django 5.2.5 on 2025-08-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_main_organisation_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_large', models.ImageField(blank=True, null=True, upload_to='organisations/')),
                ('logo_small', models.ImageField(blank=True, null=True, upload_to='organisations/')),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='main_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_mainorganisation', to='users.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='users.organisation'),
        ),
    ]
