# Generated by Django 5.2.5 on 2025-08-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_organisation_alter_user_main_organisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
                ('content', models.TextField()),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='default_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.term'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.term'),
        ),
    ]
