# Generated by Django 5.2.9 on 2025-12-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_healthmetric_acknowledged_at_delete_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_appointment_auth_token_used',
            new_name='is_auth_token_used',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='appointment_auth_token',
            new_name='one_time_auth_token',
        ),
    ]
