# Generated by Django 5.2.9 on 2026-01-06 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_is_appointment_auth_token_used_user_is_auth_token_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_notification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
