# Generated by Django 5.2.5 on 2025-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_organisation_city_organisation_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='en', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
