# Generated by Django 5.2.5 on 2025-08-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_language_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='label',
            new_name='name',
        ),
    ]
