# Generated by Django 5.2.10 on 2026-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_healthmetric_alp_u_l_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'email']},
        ),
        migrations.AddField(
            model_name='term',
            name='use_for_patient',
            field=models.BooleanField(default=False),
        ),
    ]
