# Generated by Django 5.2.5 on 2025-09-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_speciality_options_alter_speciality_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], help_text='Preferred language for the user interface', max_length=10, null=True),
        ),
    ]
