# Generated by Django 5.2.10 on 2026-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_options_term_use_for_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token used for email verification', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email address has been verified"),
        ),
    ]
