# Generated by Django 5.2.10 on 2026-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_email_verification_token_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
