# Generated by Django 5.2.5 on 2025-09-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
