# Generated by Django 5.2.6 on 2025-09-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_speciality_name_de_speciality_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
