# Generated by Django 5.2.10 on 2026-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_organisation_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Define is this organisation will be default for patient'),
        ),
    ]
