# Generated by Django 5.2.10 on 2026-02-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_organisation_is_primary_organisation_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
