# Generated by Django 5.2.6 on 2025-09-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_phone_numer',
            new_name='mobile_phone_number',
        ),
    ]
