# Generated by Django 5.2.10 on 2026-02-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_verification_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_auth_token_used',
        ),
    ]
