# Generated by Django 5.2.6 on 2025-09-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_mobile_phone_numer_user_mobile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
