# Generated by Django 5.2.10 on 2026-02-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_is_auth_token_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='one_time_auth_token',
            field=models.CharField(blank=True, help_text='Authentication token for appointment access', max_length=256, null=True),
        ),
    ]
