# Generated by Django 5.2.11 on 2026-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_city_user_country_user_postal_code_user_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
