# Generated by Django 5.2.11 on 2026-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_organisation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
