# Generated by Django 5.2.11 on 2026-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_organisation_imported_user_imported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True, help_text='Whether to show the first login dialog asking for preferred language and communication methods'),
        ),
    ]
