# Generated by Django 5.2.11 on 2026-05-15 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_encryption_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAVAppPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, help_text='Random token used as password in Basic Auth', max_length=256, unique=True)),
                ('label', models.CharField(help_text="Human-readable label, e.g. 'iPhone CardDAV'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this token was used to authenticate', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dav_app_passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DAV app password',
                'verbose_name_plural': 'DAV app passwords',
                'ordering': ['-created_at'],
            },
        ),
    ]
