# Generated by Django 5.2.11 on 2026-05-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_davapppassword'),
        ('users', '0042_user_external_id'),
    ]

    operations = [
    ]
