# Generated by Django 5.2.11 on 2026-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_merge_0042_davapppassword_0042_user_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='footer_patient_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_practitioner_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_patient_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_practitioner_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='term',
            name='content_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_uk',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('uk', 'Ukrainian')], help_text='Preferred language for the user interface', max_length=10, null=True),
        ),
    ]
