# Generated by Django 5.2.11 on 2026-06-25 16:04

import re

from django.db import migrations


def normalize(value):
    if not value:
        return value
    return re.sub(r"[\s\-.() ]", "", value.strip()) or None


def normalize_phone_numbers(apps, schema_editor):
    """Rewrite existing phone numbers to their canonical (separator-free) form.

    mobile_phone_number is unique; if normalization would collide with an
    already-normalized number, the row is left untouched to avoid breaking the
    constraint (the duplicate can be resolved manually).
    """
    User = apps.get_model("users", "User")
    seen = set()
    # Process already-canonical numbers first so they win the unique slot.
    for user in User.objects.exclude(mobile_phone_number__isnull=True).exclude(
        mobile_phone_number=""
    ):
        raw = user.mobile_phone_number
        new = normalize(raw)
        if new and new == raw:
            seen.add(new)
    for user in User.objects.exclude(mobile_phone_number__isnull=True).exclude(
        mobile_phone_number=""
    ):
        raw = user.mobile_phone_number
        new = normalize(raw)
        if not new or new == raw:
            continue
        if new in seen:
            continue
        seen.add(new)
        user.mobile_phone_number = new
        user.save(update_fields=["mobile_phone_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_organisation_footer_patient_uk_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers, migrations.RunPython.noop),
    ]
