# Generated by Django 5.2.11 on 2026-08-12 12:46

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def check_no_case_insensitive_duplicates(apps, schema_editor):
    """Fail early, with the full list, when the constraint cannot be applied.

    PostgreSQL would refuse to build the unique index anyway, but it only
    reports the first conflicting value. On a multi-tenant deployment that means
    running the upgrade once per duplicate to discover them all, so list them
    upfront instead. Use `manage.py duplicate_emails` to inspect the accounts
    before merging or deleting them.
    """
    User = apps.get_model("users", "User")

    duplicates = (
        User.objects.exclude(email__isnull=True)
        .exclude(email="")
        .annotate(lowered=Lower("email"))
        .values("lowered")
        .annotate(total=Count("pk"))
        .filter(total__gt=1)
        .order_by("lowered")
    )

    if not duplicates:
        return

    details = []
    for duplicate in duplicates:
        ids = list(
            User.objects.filter(email__iexact=duplicate["lowered"])
            .order_by("pk")
            .values_list("pk", flat=True)
        )
        details.append(f"  {duplicate['lowered']}: users {ids}")

    schema = getattr(schema_editor.connection, "schema_name", "?")
    raise RuntimeError(
        "Cannot enforce case-insensitive uniqueness on User.email in schema "
        f"'{schema}': these addresses are used by several accounts. Merge or "
        "delete the duplicates, then re-run the migration.\n"
        + "\n".join(details)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0047_speciality_icon'),
    ]

    operations = [
        migrations.RunPython(
            check_no_case_insensitive_duplicates,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_case_insensitive_unique'),
        ),
    ]
