# Generated by Django 5.2.11 on 2026-08-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_user_user_email_case_insensitive_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='footer_patient_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_practitioner_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_patient_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_practitioner_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='term',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_ar',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('uk', 'Ukrainian')], help_text='Preferred language for the user interface', max_length=10, null=True),
        ),
    ]
